[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_GEMINI_API_KEY = "your_gemini_api_key_here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
